server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lw_app?useSSL=FALSE
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost
      port: 6379
      password: 123456

Mybatis-Plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl